/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    '../{{ cookiecutter.project_slug }}/templates/**/*.html',
    '../{{ cookiecutter.project_slug }}/**/templates/**/*.html',
    '../{{ cookiecutter.project_slug }}/static/js/**/*.js',
    './node_modules/flowbite/**/*.js',
  ],
  theme: {
    extend: {
      colors: {
        error: "#F97D7D",
        success: "#409CFF",
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
      },
      fontFamily: {
        sans: [
          'Inter',
          '"Noto Sans JP"',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          '"Helvetica Neue"',
          'Arial',
          '"ヒラギノ角ゴ Pro W3"',
          '"Hiragino Kaku Gothic Pro"',
          'メイリオ',
          'Meiryo',
          '"MS Pゴシック"',
          '"MS PGothic"',
          'sans-serif',
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
        ja: [
          '"Noto Sans JP"',
          '"游ゴシック"',
          '"Yu Gothic"',
          '游ゴシック体',
          'YuGothic',
          '"ヒラギノ角ゴ Pro W3"',
          '"Hiragino Kaku Gothic Pro"',
          'メイリオ',
          'Meiryo',
          '"MS Pゴシック"',
          '"MS PGothic"',
          'sans-serif',
        ],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
    require('@tailwindcss/aspect-ratio'),
    require('@tailwindcss/line-clamp'),
    require('flowbite/plugin'),
  ],
}
